"""
Export Service - Part 2 Feature
Generates professional Excel (.xlsx) reports from dashboard data.
PDF is handled client-side via browser print (no heavy library needed on free tier).
"""
import io
from datetime import datetime
from typing import Dict, Any, List, Optional
import openpyxl
from openpyxl.styles import (
    Font, PatternFill, Alignment, Border, Side, GradientFill
)
from openpyxl.utils import get_column_letter


# ── Color palette ──────────────────────────────────────────────────────────────
DARK_BG     = "1E293B"   # slate-800
HEADER_BG   = "312E81"   # indigo-900
ACCENT_BG   = "4F46E5"   # indigo-600
GREEN_BG    = "14532D"   # green-900
AMBER_BG    = "78350F"   # amber-900
WHITE_FONT  = "FFFFFF"
LIGHT_FONT  = "CBD5E1"   # slate-300
GOLD_FONT   = "FCD34D"   # amber-300
GREEN_FONT  = "4ADE80"   # green-400

def _border(color="334155"):
    side = Side(style="thin", color=color)
    return Border(left=side, right=side, top=side, bottom=side)

def _header_font(bold=True, size=11, color=WHITE_FONT):
    return Font(name="Calibri", bold=bold, size=size, color=color)

def _cell_font(size=10, color=LIGHT_FONT, bold=False):
    return Font(name="Calibri", size=size, color=color, bold=bold)

def _fill(hex_color: str):
    return PatternFill(start_color=hex_color, end_color=hex_color, fill_type="solid")

def _center():
    return Alignment(horizontal="center", vertical="center", wrap_text=True)

def _left():
    return Alignment(horizontal="left", vertical="center", wrap_text=True)


def generate_excel_report(
    stats: Dict[str, Any],
    insights: Optional[Dict[str, Any]],
    smart_pills: Optional[List[Dict]],
    user_email: str,
    user_role: str,
) -> bytes:
    """
    Build a professional multi-sheet Excel report and return as bytes.
    Sheets:
      1. Executive Summary
      2. AI Insights
      3. Smart Analytics
      4. Audit Log
    """
    wb = openpyxl.Workbook()

    # ── Sheet 1: Executive Summary ─────────────────────────────────────────────
    ws1 = wb.active
    ws1.title = "Executive Summary"
    ws1.sheet_view.showGridLines = False
    ws1.column_dimensions["A"].width = 32
    ws1.column_dimensions["B"].width = 22
    ws1.column_dimensions["C"].width = 22
    ws1.column_dimensions["D"].width = 22

    # Title block
    ws1.merge_cells("A1:D1")
    ws1["A1"] = "InsightAI – Executive Intelligence Report"
    ws1["A1"].font      = Font(name="Calibri", bold=True, size=16, color=GOLD_FONT)
    ws1["A1"].fill      = _fill(HEADER_BG)
    ws1["A1"].alignment = _center()
    ws1.row_dimensions[1].height = 36

    ws1.merge_cells("A2:D2")
    now = datetime.utcnow().strftime("%B %d, %Y  %H:%M UTC")
    ws1["A2"] = f"Generated by: {user_email}  ({user_role})    |    {now}"
    ws1["A2"].font      = _cell_font(size=9, color="94A3B8")
    ws1["A2"].fill      = _fill(DARK_BG)
    ws1["A2"].alignment = _center()
    ws1.row_dimensions[2].height = 18

    ws1.append([])   # blank row

    # KPI header row
    kpi_headers = ["KPI Metric", "Value", "Description", "Status"]
    ws1.append(kpi_headers)
    row = ws1.max_row
    for col, _ in enumerate(kpi_headers, 1):
        cell = ws1.cell(row=row, column=col)
        cell.font      = _header_font(size=10)
        cell.fill      = _fill(ACCENT_BG)
        cell.alignment = _center()
        cell.border    = _border()
    ws1.row_dimensions[row].height = 22

    # KPI data rows
    kpis = [
        ("Total Spreadsheets Loaded",  stats.get("total_files", 0),    "All file versions in registry",            "✅ Active"),
        ("Approved Datasets",           stats.get("total_approved", 0), "Available for AI Chat & Query",            "✅ Live"),
        ("Active Alert Rules",          stats.get("total_rules", 0),    "Rules Engine triggers configured",          "✅ Monitoring"),
        ("Smart Insight Pills",         len(smart_pills) if smart_pills else 0, "Auto-detected business signals", "✅ Generated"),
    ]
    for kpi in kpis:
        ws1.append(list(kpi))
        row = ws1.max_row
        bg = "0F172A" if row % 2 == 0 else "1E293B"
        for col in range(1, 5):
            cell = ws1.cell(row=row, column=col)
            cell.font      = _cell_font()
            cell.fill      = _fill(bg)
            cell.alignment = _left()
            cell.border    = _border()
        ws1.row_dimensions[row].height = 20

    # ── Sheet 2: AI Insights ───────────────────────────────────────────────────
    ws2 = wb.create_sheet("AI Insights")
    ws2.sheet_view.showGridLines = False
    ws2.column_dimensions["A"].width = 6
    ws2.column_dimensions["B"].width = 80

    ws2.merge_cells("A1:B1")
    ws2["A1"] = "Gemini AI – Business Intelligence Insights"
    ws2["A1"].font      = Font(name="Calibri", bold=True, size=14, color=GOLD_FONT)
    ws2["A1"].fill      = _fill(HEADER_BG)
    ws2["A1"].alignment = _center()
    ws2.row_dimensions[1].height = 32

    # Key Findings
    ws2.merge_cells("A3:B3")
    ws2["A3"] = "KEY DIAGNOSTICS"
    ws2["A3"].font      = _header_font(size=11, color=GOLD_FONT)
    ws2["A3"].fill      = _fill("1E3A5F")
    ws2["A3"].alignment = _left()
    ws2.row_dimensions[3].height = 24

    findings = (insights or {}).get("key_findings", ["No insights available. Approve datasets to generate."])
    for i, finding in enumerate(findings, 1):
        ws2.cell(row=3+i, column=1).value = f"{i}."
        ws2.cell(row=3+i, column=1).font  = _cell_font(color=GOLD_FONT, bold=True)
        ws2.cell(row=3+i, column=1).fill  = _fill("0F172A")
        ws2.cell(row=3+i, column=2).value = finding
        ws2.cell(row=3+i, column=2).font  = _cell_font(size=10, color="E2E8F0")
        ws2.cell(row=3+i, column=2).fill  = _fill("0F172A")
        ws2.cell(row=3+i, column=2).alignment = _left()
        ws2.row_dimensions[3+i].height = 20

    # Recommendations
    rec_start = 3 + len(findings) + 2
    ws2.cell(row=rec_start, column=1).value = "ACTION RECOMMENDATIONS"
    ws2.merge_cells(f"A{rec_start}:B{rec_start}")
    ws2.cell(row=rec_start, column=1).font      = _header_font(size=11, color=GREEN_FONT)
    ws2.cell(row=rec_start, column=1).fill      = _fill("14532D")
    ws2.cell(row=rec_start, column=1).alignment = _left()
    ws2.row_dimensions[rec_start].height = 24

    recs = (insights or {}).get("recommendations", ["Upload and approve data files to get recommendations."])
    for i, rec in enumerate(recs, 1):
        r = rec_start + i
        ws2.cell(row=r, column=1).value = f"{i}."
        ws2.cell(row=r, column=1).font  = _cell_font(color=GREEN_FONT, bold=True)
        ws2.cell(row=r, column=1).fill  = _fill("0F172A")
        ws2.cell(row=r, column=2).value = rec
        ws2.cell(row=r, column=2).font  = _cell_font(size=10, color="E2E8F0")
        ws2.cell(row=r, column=2).fill  = _fill("0F172A")
        ws2.cell(row=r, column=2).alignment = _left()
        ws2.row_dimensions[r].height = 20

    # ── Sheet 3: Smart Analytics Pills ────────────────────────────────────────
    ws3 = wb.create_sheet("Smart Analytics")
    ws3.sheet_view.showGridLines = False
    ws3.column_dimensions["A"].width = 38
    ws3.column_dimensions["B"].width = 18
    ws3.column_dimensions["C"].width = 12
    ws3.column_dimensions["D"].width = 28

    ws3.merge_cells("A1:D1")
    ws3["A1"] = "Smart Analytics – Auto-Detected Business Signals"
    ws3["A1"].font      = Font(name="Calibri", bold=True, size=13, color=GOLD_FONT)
    ws3["A1"].fill      = _fill(HEADER_BG)
    ws3["A1"].alignment = _center()
    ws3.row_dimensions[1].height = 30

    hdrs = ["Signal / Metric", "Value", "Trend", "Source Table"]
    ws3.append(hdrs)
    row = ws3.max_row
    for col in range(1, 5):
        cell = ws3.cell(row=row, column=col)
        cell.font      = _header_font()
        cell.fill      = _fill(ACCENT_BG)
        cell.alignment = _center()
        cell.border    = _border()
    ws3.row_dimensions[row].height = 22

    if smart_pills:
        for pill in smart_pills:
            trend_icon = {"up": "↑ Rising", "down": "↓ Falling", "warning": "⚠ Anomaly", "neutral": "→ Stable"}.get(pill.get("trend","neutral"), "→ Stable")
            ws3.append([pill.get("label",""), pill.get("value",""), trend_icon, pill.get("table","")])
            row = ws3.max_row
            bg = "0F172A" if row % 2 == 0 else "1E293B"
            trend = pill.get("trend", "neutral")
            trend_color = {"up": GREEN_FONT, "down": "F87171", "warning": "FCD34D", "neutral": "94A3B8"}.get(trend, "94A3B8")
            for col in range(1, 5):
                cell = ws3.cell(row=row, column=col)
                cell.fill      = _fill(bg)
                cell.alignment = _left()
                cell.border    = _border()
                if col == 3:
                    cell.font = _cell_font(color=trend_color, bold=True)
                else:
                    cell.font = _cell_font()
            ws3.row_dimensions[row].height = 20
    else:
        ws3.append(["No approved datasets found.", "", "", ""])

    # ── Sheet 4: Audit Log ─────────────────────────────────────────────────────
    ws4 = wb.create_sheet("Audit Log")
    ws4.sheet_view.showGridLines = False
    ws4.column_dimensions["A"].width = 22
    ws4.column_dimensions["B"].width = 28
    ws4.column_dimensions["C"].width = 55

    ws4.merge_cells("A1:C1")
    ws4["A1"] = "System Audit Trail"
    ws4["A1"].font      = Font(name="Calibri", bold=True, size=13, color=WHITE_FONT)
    ws4["A1"].fill      = _fill(HEADER_BG)
    ws4["A1"].alignment = _center()
    ws4.row_dimensions[1].height = 28

    hdrs4 = ["Timestamp", "Action", "Details"]
    ws4.append(hdrs4)
    row = ws4.max_row
    for col in range(1, 4):
        cell = ws4.cell(row=row, column=col)
        cell.font      = _header_font()
        cell.fill      = _fill(ACCENT_BG)
        cell.alignment = _center()
        cell.border    = _border()
    ws4.row_dimensions[row].height = 22

    recent_logs = stats.get("recent_logs", [])
    for log in recent_logs:
        ts = log.get("timestamp", "")
        if ts:
            try:
                ts = datetime.fromisoformat(str(ts).replace("Z","")).strftime("%Y-%m-%d %H:%M:%S")
            except Exception:
                ts = str(ts)
        ws4.append([ts, log.get("action",""), log.get("details","")])
        row = ws4.max_row
        bg = "0F172A" if row % 2 == 0 else "1E293B"
        for col in range(1, 4):
            cell = ws4.cell(row=row, column=col)
            cell.font      = _cell_font()
            cell.fill      = _fill(bg)
            cell.alignment = _left()
            cell.border    = _border()
        ws4.row_dimensions[row].height = 20

    # ── Serialize to bytes ─────────────────────────────────────────────────────
    buf = io.BytesIO()
    wb.save(buf)
    buf.seek(0)
    return buf.read()
